<a href="https://colab.research.google.com/github/PUHUPAGARWAL1515/Python-codes/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Purpose: NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

Advantages:

Efficient Array Operations: NumPy's core is the ndarray (n-dimensional array), which is significantly faster than Python lists for numerical computations.
Broadcasting: Enables operations on arrays with different shapes, reducing the need for explicit loops.
Mathematical Functions: Offers a wide range of mathematical, statistical, and linear algebra functions.
Integration with Other Libraries: NumPy arrays are the standard data structure for libraries like SciPy, Pandas, and Scikit-learn, making it a cornerstone of the scientific Python ecosystem.
Enhancement: NumPy enhances Python's capabilities by providing a powerful and efficient tool for handling numerical data, making it suitable for tasks ranging from simple calculations to complex data analysis and machine learning.

In [ ]:
2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean(): Calculates the arithmetic mean (average) of the elements along a given axis. It doesn't consider weights.

np.average(): Calculates the weighted average of the elements along a given axis. You can provide weights to give certain elements more importance in the average.

When to use which:

Use np.mean() when you want the simple average without considering any weights.
Use np.average() when you need to calculate a weighted average, where some elements contribute more to the final result than others.

In [ ]:
3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

np.flip(): Reverses the order of elements along a given axis in an array.
1D ARRAY:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)  # Output: [5 4 3 2 1]
2D ARRAY:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
reversed_rows = np.flip(arr_2d, axis=0)  # Reverse along rows
reversed_cols = np.flip(arr_2d, axis=1)  # Reverse along columns
print(reversed_rows)
print(reversed_cols)

In [ ]:
4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32, depending on the system)
Importance of Data Types:

Memory Management: Choosing the right data type is crucial for efficient memory usage. For example, using int8 instead of int64 can significantly reduce memory consumption if you know your integers will be small.
Performance: NumPy operations are much faster when the data type is consistent and optimized. Operations on arrays with mixed data types can be slower.



In [ ]:
5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarrays (n-dimensional arrays): The core data structure in NumPy. They are homogeneous, multi-dimensional arrays that store elements of the same data type.

Key Features:

Homogeneous: All elements have the same data type.
Multi-dimensional: Can represent vectors, matrices, and higher-dimensional data.
Fixed Size: The size of an ndarray is fixed when it's created.
Efficient Operations: NumPy provides optimized functions for performing operations on ndarrays.
Differences from Python Lists:

Speed: ndarrays are significantly faster for numerical operations due to their homogeneous nature and optimized implementation.
Memory Efficiency: ndarrays are more memory-efficient than Python lists, especially for large datasets.
Functionality: NumPy provides a wide range of mathematical and scientific functions specifically designed for ndarrays.

In [ ]:
6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Contiguous Memory Allocation: NumPy arrays store elements in contiguous memory blocks, allowing for faster access and processing.
Vectorized Operations: NumPy operations are vectorized, meaning they are performed on entire arrays at once, eliminating the need for explicit loops (which are slow in Python).
Optimized Implementation: NumPy is implemented in C and Fortran, making it much faster than pure Python code.

In [ ]:
7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

vstack() (Vertical Stack): Stacks arrays in sequence vertically (row-wise).

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)
# Output:
# [[1 2 3]
#  [4 5 6]]
hstack() (Horizontal Stack): Stacks arrays in sequence horizontally (column-wise).
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))
print(c)
# Output: [1 2 3 4 5 6]


In [ ]:
8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

fliplr() (Flip Left-Right): Flips an array horizontally (along the columns). It reverses the order of columns in each row. It works on 2D arrays.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_lr = np.fliplr(arr)
print(flipped_lr)
# Output:
# [[3 2 1]
#  [6 5 4]]
flipud() (Flip Up-Down): Flips an array vertically (along the rows). It reverses the order of rows. It works on 2D arrays.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_ud = np.flipud(arr)
print(flipped_ud)
# Output:
# [[4 5 6]
#  [1 2 3]]


In [ ]:
9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

array_split(): Splits an array into multiple sub-arrays along a specified axis.

Uneven Splits: If the array cannot be divided evenly, array_split() will distribute the remaining elements to the first few sub-arrays, resulting in sub-arrays of different sizes
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arr = np.array_split(arr, 3)
print(split_arr)
# Output: [array([1, 2, 3]), array([4, 5]), array([6, 7])]

In [ ]:
10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization: The process of performing operations on entire arrays at once, rather than element-by-element using loops. NumPy's vectorized operations are implemented in optimized C code, making them significantly faster.

Broadcasting: A powerful mechanism that allows NumPy to perform arithmetic operations on arrays with different shapes. NumPy automatically expands the smaller array to match the shape of the larger array, enabling element-wise operations

In [ ]:
#PRACTICAL_QUESTIONS:

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns (transpose).
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

# Transpose the array (interchange rows and columns)
transposed_arr = arr.T
print("\nTransposed Array:\n", transposed_arr)

In [ ]:
#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(10)
print("1D Array:\n", arr_1d)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\n2x5 Array:\n", arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\n5x2 Array:\n", arr_5x2)

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr_4x4)

# Create a 6x6 array filled with zeros
arr_6x6 = np.zeros((6, 6))

# Copy the 4x4 array into the center of the 6x6 array
arr_6x6[1:-1, 1:-1] = arr_4x4
print("\n6x6 Array with Border of Zeros:\n", arr_6x6)

In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print("Array:\n", arr)

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original Array:\n", arr)
print("\nUppercase Array:\n", uppercase_arr)
print("\nLowercase Array:\n", lowercase_arr)
print("\nTitlecase Array:\n", titlecase_arr)

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character
spaced_words = np.array([' '.join(word) for word in words])
print("Original Array:\n", words)
print("\nSpaced Words Array:\n", spaced_words)

In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print("Identity Matrix:\n", identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers in the array
prime_numbers = arr[np.vectorize(is_prime)(arr)]
print("Array:\n", arr)
print("\nPrime Numbers:\n", prime_numbers)

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
temperatures = np.random.randint(20, 40, 30)

# Calculate weekly averages
weekly_averages = [np.mean(temperatures[i:i+7]) for i in range(0, 30, 7)]

print("Temperatures:\n", temperatures)
print("\nWeekly Averages:\n", weekly_averages)